### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pchaigno** [Lesterpig/board#1]
Hi @Lesterpig!

I'd like to use this project in our small lab but I don't know what licensing terms you're distributing it under. Any chance you could pick one from here: http://choosealicense.com?

**Comment by Lesterpig** [comment]
Hi!

Thank you for your interest.
I just chose the GNU LGPLv3 license and committed it to the repo as https://github.com/Lesterpig/board/blob/master/LICENSE

I would be very happy to read your feedbacks :smile:
